# AeroSpace Configuration
# Refactored with consistent cmd-shift-x mode switching and clean mode organization

# ============================================================================
# CORE CONFIGURATION
# ============================================================================

after-login-command = [
    'exec-and-forget sketchybar',
    'exec-and-forget borders active_color=0xff8aadf4 inactive_color=0xff494d64 width=1.5 2>/dev/null &'
]

after-startup-command = [
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main',
]

exec-on-workspace-change = [
    '/bin/bash',
    '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Visual Configuration
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Key mapping preset
key-mapping.preset = 'qwerty'

# Mouse behavior
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Gap configuration
[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 5
outer.top = 45
outer.right = 10

# ============================================================================
# MAIN MODE - Frequent operations + Mode switchers
# ============================================================================
# Most frequent operations are directly accessible with clean prefix patterns:
# - alt-hjkl = Window focus (immediate access)
# - alt-shift-hjkl = Window movement (immediate access)
# - alt-[key] = Workspace switching (immediate access)
# - cmd-alt-[key] = Move window to workspace (immediate access)
#
# Mode Switchers for advanced operations: cmd-shift-[letter]
# - cmd-shift-w = Window mode (resize, join, monitor, close operations)
# - cmd-shift-s = Space mode (advanced workspace operations)
# - cmd-shift-l = Layout mode (layouts, containers)
# - cmd-shift-a = App mode (application launching)
# - cmd-shift-m = Maintenance mode (system utilities, config, themes)
# ============================================================================

[mode.main.binding]

# ============================================================================
# MODE SWITCHERS - cmd-shift-[letter] pattern
# ============================================================================

cmd-shift-w = [
    'mode window',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh window',
]

cmd-shift-s = [
    'mode space',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh space',
]

cmd-shift-l = [
    'mode layout',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh layout',
]

cmd-shift-a = [
    'mode app',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh app',
]

cmd-shift-m = [
    'mode maintenance',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh maintenance',
]

# ============================================================================
# FREQUENT WINDOW OPERATIONS - Direct access with alt- prefix
# ============================================================================

# Window focus (vim-style navigation)
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Window movement
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# ============================================================================
# FREQUENT WORKSPACE OPERATIONS - Direct access
# ============================================================================

# Workspace switching
alt-tab = 'workspace-back-and-forth'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-a = 'workspace A'
alt-b = 'workspace B'
alt-c = 'workspace C'
alt-e = 'workspace E'
alt-t = 'workspace T'
alt-m = 'workspace M'
alt-z = 'workspace Z'

# Move window to workspace (stay on current)
cmd-alt-1 = 'move-node-to-workspace 1'
cmd-alt-2 = 'move-node-to-workspace 2'
cmd-alt-3 = 'move-node-to-workspace 3'
cmd-alt-4 = 'move-node-to-workspace 4'
cmd-alt-5 = 'move-node-to-workspace 5'
cmd-alt-a = 'move-node-to-workspace A'
cmd-alt-b = 'move-node-to-workspace B'
cmd-alt-c = 'move-node-to-workspace C'
cmd-alt-e = 'move-node-to-workspace E'
cmd-alt-t = 'move-node-to-workspace T'
cmd-alt-m = 'move-node-to-workspace M'
cmd-alt-z = 'move-node-to-workspace Z'

# ============================================================================
# ESSENTIAL SHORTCUTS
# ============================================================================

alt-f = 'fullscreen'

# Disable conflicting macOS shortcuts
cmd-h = []

# ============================================================================
# WINDOW MODE - Advanced window operations
# ============================================================================
# Advanced operations: resize, join, monitor, close (frequent ops moved to main)
# ============================================================================

[mode.window.binding]

# Exit mode
esc = [
    'mode main',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main',
]

# Resize windows
minus = 'resize smart -50'
equal = 'resize smart +50'
shift-minus = 'resize smart -100'
shift-equal = 'resize smart +100'

# Join containers
h = 'join-with left'
j = 'join-with down'
k = 'join-with up'
l = 'join-with right'

# Monitor operations
m = 'focus-monitor --wrap-around next'
shift-m = 'move-node-to-monitor --wrap-around next'
ctrl-m = 'move-node-to-monitor --wrap-around prev'

# Window operations
q = 'close'
shift-q = 'close-all-windows-but-current'
f = 'fullscreen'

# Quick mode switching
cmd-shift-l = [
    'mode layout',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh layout',
]
cmd-shift-a = [
    'mode app',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh app',
]
cmd-shift-m = [
    'mode maintenance',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh maintenance',
]

# ============================================================================
# SPACE MODE - Advanced workspace operations
# ============================================================================
# Advanced operations: move-and-follow, navigation, monitor ops (frequent ops moved to main)
# ============================================================================

[mode.space.binding]

# Exit mode
esc = [
    'mode main',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main',
]

# Move window and follow (advanced operation)
1 = ['move-node-to-workspace 1', 'workspace 1']
2 = ['move-node-to-workspace 2', 'workspace 2']
3 = ['move-node-to-workspace 3', 'workspace 3']
4 = ['move-node-to-workspace 4', 'workspace 4']
5 = ['move-node-to-workspace 5', 'workspace 5']
a = ['move-node-to-workspace A', 'workspace A']
b = ['move-node-to-workspace B', 'workspace B']
c = ['move-node-to-workspace C', 'workspace C']
e = ['move-node-to-workspace E', 'workspace E']
t = ['move-node-to-workspace T', 'workspace T']
m = ['move-node-to-workspace M', 'workspace M']
z = ['move-node-to-workspace Z', 'workspace Z']

# Workspace navigation
left = 'workspace --wrap-around prev'
right = 'workspace --wrap-around next'
up = 'workspace --wrap-around prev'
down = 'workspace --wrap-around next'
tab = 'workspace-back-and-forth'

# Move workspaces between monitors
shift-left = 'move-workspace-to-monitor --wrap-around prev'
shift-right = 'move-workspace-to-monitor --wrap-around next'

# Quick mode switching
cmd-shift-w = [
    'mode window',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh window',
]
cmd-shift-l = [
    'mode layout',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh layout',
]
cmd-shift-a = [
    'mode app',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh app',
]

# ============================================================================
# LAYOUT MODE - Layout switching and container operations
# ============================================================================
# Layout types, container operations
# ============================================================================

[mode.layout.binding]

# Exit mode
esc = [
    'mode main',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main',
]

# Layout types
t = 'layout tiles horizontal vertical'
c = 'layout accordion horizontal vertical'
f = 'layout floating tiling'

# Orientation control
h = 'layout tiles horizontal'
v = 'layout tiles vertical'

# Container operations
r = 'flatten-workspace-tree'
b = 'balance-sizes'

# Quick layout switching
slash = 'layout tiles horizontal vertical'
comma = 'layout accordion horizontal vertical'
period = 'layout floating tiling'

# Quick mode switching
cmd-shift-w = [
    'mode window',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh window',
]
cmd-shift-a = [
    'mode app',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh app',
]
cmd-shift-m = [
    'mode maintenance',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh maintenance',
]

# ============================================================================
# APP MODE - Application launching
# ============================================================================
# Launch applications with semantic keys matching workspace assignments
# ============================================================================

[mode.app.binding]

# Exit mode
esc = [
    'mode main',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main',
]

# Application launching (semantic keys)
t = 'exec-and-forget open -na "Alacritty"'
b = 'exec-and-forget open -na "Google Chrome" --args --profile-directory="Default"'
shift-b = 'exec-and-forget open -a "Google Chrome" --args --profile-directory="Profile 1"'
s = 'exec-and-forget open -na "Safari"'
e = 'exec-and-forget open -a "Zed"'
shift-e = 'exec-and-forget open -a "Emacs"'
c = 'exec-and-forget open -a "Calendar"'
a = 'exec-and-forget open -a "ChatGPT"'
m = 'exec-and-forget open -a "Messages"'
f = 'exec-and-forget open -a "Finder"'
n = 'exec-and-forget open -a "Notes"'

# Quick mode switching
cmd-shift-w = [
    'mode window',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh window',
]
cmd-shift-s = [
    'mode space',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh space',
]
cmd-shift-m = [
    'mode maintenance',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh maintenance',
]

# ============================================================================
# MAINTENANCE MODE - System utilities and configuration
# ============================================================================
# Less frequently used system operations, config management, themes
# ============================================================================

[mode.maintenance.binding]

# Exit mode
esc = [
    'mode main',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main',
]

# Configuration management
r = 'reload-config'
shift-r = 'exec-and-forget killall AeroSpace && open -a AeroSpace'

# Theme and visual management
t = 'exec-and-forget ~/.config/sketchybar/themes/theme-manager.sh'

# System utilities
s = 'exec-and-forget screencapture -i -c'
shift-s = 'exec-and-forget screencapture -i ~/Desktop/screenshot-$(date +%Y%m%d-%H%M%S).png'


# Quick mode switching
cmd-shift-w = [
    'mode window',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh window',
]
cmd-shift-s = [
    'mode space',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh space',
]
cmd-shift-l = [
    'mode layout',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh layout',
]

# ============================================================================
# AUTOMATIC WINDOW ASSIGNMENT
# ============================================================================

# Terminal apps → Workspace T
[[on-window-detected]]
if.app-id = 'org.alacritty'
run = "move-node-to-workspace T"

[[on-window-detected]]
if.app-id = 'dev.warp.Warp-Stable'
run = "move-node-to-workspace T"

# Browser apps → Workspace B
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = "move-node-to-workspace B"

# Editor apps → Workspace E
[[on-window-detected]]
if.app-id = 'dev.zed.Zed'
run = "move-node-to-workspace E"

[[on-window-detected]]
if.app-id = 'org.gnu.Emacs'
run = "move-node-to-workspace E"

[[on-window-detected]]
if.app-id = 'com.todesktop.230313mzl4w4u92'
run = "move-node-to-workspace E"

# AI tools → Workspace A
[[on-window-detected]]
if.app-id = 'com.openai.chat'
run = "move-node-to-workspace A"

[[on-window-detected]]
if.app-id = 'com.google.Chrome.app.caidcmannjgahlnbpmidmiecjcoiiigg'
run = "move-node-to-workspace A"

# Calendar → Workspace C
[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = "move-node-to-workspace C"

# Messages → Workspace M
[[on-window-detected]]
if.app-id = 'com.google.Chrome.app.mdpkiolbdkhdjpekfbkbmhigcaggjagi'
run = "move-node-to-workspace M"

# Meeting → Workspace Z
[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = "move-node-to-workspace Z"
