# AeroSpace Configuration
# Refactored with consistent alt-ctrl-x mode switching and clean mode organization

# ============================================================================
# CORE CONFIGURATION
# ============================================================================


after-startup-command = [
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main',
]

exec-on-workspace-change = [
    '/bin/bash',
    '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Visual Configuration
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Key mapping preset
key-mapping.preset = 'qwerty'

# Mouse behavior
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Gap configuration
[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 5
outer.top = 45
outer.right = 10

# ============================================================================
# MAIN MODE - Frequent operations + Mode switchers
# ============================================================================
# Most frequent operations are directly accessible with clean prefix patterns:
# - alt-hjkl = Window focus (immediate access)
# - alt-shift-hjkl = Window movement (immediate access)
# - alt-[1-3,letters] = Workspace switching (immediate access)
# - cmd-alt-[1-3,letters] = Move window to workspace (immediate access)
#
# Mode Switchers for advanced operations: alt-ctrl-[letter]
# - alt-ctrl-w = Window mode (resize, join, monitor, close operations)
# - alt-ctrl-s = Space mode (advanced workspace operations)
# - alt-ctrl-l = Layout mode (layouts, containers)
# - alt-ctrl-a = App mode (application launching)
# - alt-ctrl-m = Maintenance mode (system utilities, config, themes)
# ============================================================================

[mode.main.binding]

# ============================================================================
# MODE SWITCHERS - alt-ctrl-[letter] pattern
# ============================================================================

alt-ctrl-w = [
    'mode window',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh window',
]

alt-ctrl-s = [
    'mode space',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh space',
]

alt-ctrl-l = [
    'mode layout',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh layout',
]

alt-ctrl-a = [
    'mode app',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh app',
]

alt-ctrl-m = [
    'mode maintenance',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh maintenance',
]

# ============================================================================
# FREQUENT WINDOW OPERATIONS - Direct access with alt- prefix
# ============================================================================

# Window focus (vim-style navigation)
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Window movement
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# ============================================================================
# FREQUENT WORKSPACE OPERATIONS - Direct access
# ============================================================================

# Workspace switching
alt-tab = 'workspace-back-and-forth'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-a = 'workspace A'
alt-b = 'workspace B'
alt-c = 'workspace C'
alt-e = 'workspace E'
alt-t = 'workspace T'
alt-m = 'workspace M'
alt-z = 'workspace Z'

# Move window to workspace (stay on current)
cmd-alt-1 = 'move-node-to-workspace 1'
cmd-alt-2 = 'move-node-to-workspace 2'
cmd-alt-3 = 'move-node-to-workspace 3'
cmd-alt-a = 'move-node-to-workspace A'
cmd-alt-b = 'move-node-to-workspace B'
cmd-alt-c = 'move-node-to-workspace C'
cmd-alt-e = 'move-node-to-workspace E'
cmd-alt-t = 'move-node-to-workspace T'
cmd-alt-m = 'move-node-to-workspace M'
cmd-alt-z = 'move-node-to-workspace Z'

# ============================================================================
# ESSENTIAL SHORTCUTS
# ============================================================================

alt-f = 'fullscreen'

# Disable conflicting macOS shortcuts
cmd-h = []
cmd-enter = 'exec-and-forget open -na Alacritty'

# ============================================================================
# WINDOW MODE - Advanced window operations
# ============================================================================
# Advanced operations: resize, join, monitor, close (frequent ops moved to main)
# ============================================================================

[mode.window.binding]

# Exit mode
esc = [
    'mode main',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main',
]

# Resize windows
minus = ['resize smart -50', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
equal = ['resize smart +50', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
shift-minus = ['resize smart -100', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
shift-equal = ['resize smart +100', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']

# Join containers
h = ['join-with left', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
j = ['join-with down', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
k = ['join-with up', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
l = ['join-with right', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']

# Monitor operations
m = ['focus-monitor --wrap-around next', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
shift-m = ['move-node-to-monitor --wrap-around next', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
ctrl-m = ['move-node-to-monitor --wrap-around prev', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']

# Window operations
q = ['close', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
shift-q = ['close-all-windows-but-current', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
f = ['fullscreen', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']

# Quick mode switching
alt-ctrl-l = [
    'mode layout',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh layout',
]
alt-ctrl-a = [
    'mode app',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh app',
]
alt-ctrl-m = [
    'mode maintenance',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh maintenance',
]

# ============================================================================
# SPACE MODE - Advanced workspace operations
# ============================================================================
# Advanced operations: move-and-follow, navigation, monitor ops (frequent ops moved to main)
# ============================================================================

[mode.space.binding]

# Exit mode
esc = [
    'mode main',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main',
]

# Move window and follow (advanced operation)
1 = ['move-node-to-workspace 1', 'workspace 1', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
2 = ['move-node-to-workspace 2', 'workspace 2', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
3 = ['move-node-to-workspace 3', 'workspace 3', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
a = ['move-node-to-workspace A', 'workspace A', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
b = ['move-node-to-workspace B', 'workspace B', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
c = ['move-node-to-workspace C', 'workspace C', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
e = ['move-node-to-workspace E', 'workspace E', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
t = ['move-node-to-workspace T', 'workspace T', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
m = ['move-node-to-workspace M', 'workspace M', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
z = ['move-node-to-workspace Z', 'workspace Z', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']

# Workspace navigation
left = ['workspace --wrap-around prev', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
right = ['workspace --wrap-around next', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
up = ['workspace --wrap-around prev', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
down = ['workspace --wrap-around next', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
tab = ['workspace-back-and-forth', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']

# Move workspaces between monitors
shift-left = ['move-workspace-to-monitor --wrap-around prev', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
shift-right = ['move-workspace-to-monitor --wrap-around next', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']

# Quick mode switching
alt-ctrl-w = [
    'mode window',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh window',
]
alt-ctrl-l = [
    'mode layout',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh layout',
]
alt-ctrl-a = [
    'mode app',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh app',
]

# ============================================================================
# LAYOUT MODE - Layout switching and container operations
# ============================================================================
# Layout types, container operations
# ============================================================================

[mode.layout.binding]

# Exit mode
esc = [
    'mode main',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main',
]

# Layout types
t = ['layout tiles horizontal vertical', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
c = ['layout accordion horizontal vertical', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
f = ['layout floating tiling', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']

# Orientation control
h = ['layout tiles horizontal', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
v = ['layout tiles vertical', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']

# Container operations
r = ['flatten-workspace-tree', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
b = ['balance-sizes', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']

# Quick layout switching
slash = ['layout tiles horizontal vertical', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
comma = ['layout accordion horizontal vertical', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
period = ['layout floating tiling', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']

# Quick mode switching
alt-ctrl-w = [
    'mode window',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh window',
]
alt-ctrl-a = [
    'mode app',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh app',
]
alt-ctrl-m = [
    'mode maintenance',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh maintenance',
]

# ============================================================================
# APP MODE - Application launching
# ============================================================================
# Launch applications with semantic keys matching workspace assignments
# ============================================================================

[mode.app.binding]

# Exit mode
esc = [
    'mode main',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main',
]

# Application launching (semantic keys)
t = ['exec-and-forget open -na "Warp"', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
b = ['exec-and-forget open -na "Google Chrome" --args --profile-directory="Default"', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
shift-b = ['exec-and-forget open -a "Google Chrome" --args --profile-directory="Profile 1"', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
s = ['exec-and-forget open -na "Safari"', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
z = ['exec-and-forget open -na "Zed"', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
e = ['exec-and-forget open -a "Emacs"', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
c = ['exec-and-forget open -a "Calendar"', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
shift-c = ['exec-and-forget open -a "Google Chat"', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
a = ['exec-and-forget open -a "ChatGPT"', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
m = ['exec-and-forget open -a "Mail"', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
f = ['exec-and-forget open -a "Finder"', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']

# Quick mode switching
alt-ctrl-w = [
    'mode window',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh window',
]
alt-ctrl-s = [
    'mode space',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh space',
]
alt-ctrl-m = [
    'mode maintenance',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh maintenance',
]

# ============================================================================
# MAINTENANCE MODE - System utilities and configuration
# ============================================================================
# Less frequently used system operations, config management, themes
# ============================================================================

[mode.maintenance.binding]

# Exit mode
esc = [
    'mode main',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main',
]

# Configuration management
r = ['reload-config', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
shift-r = ['exec-and-forget killall AeroSpace && open -a AeroSpace', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']

# Theme and visual management
t = ['exec-and-forget ~/.config/sketchybar/themes/theme-manager.sh', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']

# System utilities
s = ['exec-and-forget screencapture -i -c ~/Desktop/screenshot-$(date +%Y%m%d-%H%M%S).png', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']
shift-s = ['exec-and-forget screencapture -i ~/Desktop/screenshot-$(date +%Y%m%d-%H%M%S).png', 'mode main', 'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh main']

# Quick mode switching
alt-ctrl-w = [
    'mode window',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh window',
]
alt-ctrl-s = [
    'mode space',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh space',
]
alt-ctrl-l = [
    'mode layout',
    'exec-and-forget ~/.config/sketchybar/plugins/workspace/aerospace_mode.sh layout',
]

# ============================================================================
# AUTOMATIC WINDOW ASSIGNMENT
# ============================================================================

# Terminal apps → Workspace T
[[on-window-detected]]
if.app-id = 'org.alacritty'
run = "move-node-to-workspace T"

[[on-window-detected]]
if.app-id = 'dev.warp.Warp-Stable'
run = "move-node-to-workspace T"

# Browser apps → Workspace B
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = "move-node-to-workspace B"

# Editor apps → Workspace E
[[on-window-detected]]
if.app-id = 'dev.zed.Zed'
run = "move-node-to-workspace E"

[[on-window-detected]]
if.app-id = 'org.gnu.Emacs'
run = "move-node-to-workspace E"

[[on-window-detected]]
if.app-id = 'com.todesktop.230313mzl4w4u92'
run = "move-node-to-workspace E"

# AI tools → Workspace A
[[on-window-detected]]
if.app-id = 'com.openai.chat'
run = "move-node-to-workspace A"

[[on-window-detected]]
if.app-id = 'com.google.Chrome.app.caidcmannjgahlnbpmidmiecjcoiiigg'
run = "move-node-to-workspace A"

# Calendar → Workspace C
[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = "move-node-to-workspace C"

# Messages → Workspace M
[[on-window-detected]]
if.app-id = 'com.google.Chrome.app.mdpkiolbdkhdjpekfbkbmhigcaggjagi'
run = "move-node-to-workspace M"

# Meeting → Workspace Z
[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = "move-node-to-workspace Z"
